version: "3"

services:
  ### [APP Server]
  frontend:
    container_name: nuxt
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      # - /app/node_modules # 호스트 디렉토리에 node_modules 는 없기에 컨테이너에 맵핑을 하지 말라고 하는 것
      - nodemodules:/app/node_modules:ro # UUID local 볼륨 생성 방지
    restart: always
    # ports:
      # - "3000:3000"
    expose:
      - 3000
    environment:
      # - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - API_URL=http://172.18.0.2:5000/api
      - API_URL_BROWSER=https://zempotdocker.com/api
      # - CHOKIDAR_USEPOLLING=true # Hot Reload 기능 사용
    command: "npm run dev"
    depends_on:
      - backend
    networks:
      - zempot-net

  ### [API Server]
  backend:
    container_name: dotnet
    build:
      context: ./backend
      dockerfile: Dockerfile
    # volumes:
      # - ./backend:/app:ro
      # - /app/core.Api/bin
      # - /app/core.Api/obj
    restart: always
    ports:
      - "5000:5000"
    expose:
      - 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:443;http://+:8080
      - ASPNETCORE_URLS=http://+:5000
    networks:
      # - internal
      - zempot-net

volumes:
  nodemodules:
    external: true # 기존에 만들어 둔 nodemodules 을 사용한다

networks:
  # internal:
  zempot-net:
    external: true # 새 network 가 만들어지지 않고, 기존 network 에 연결되게 하는 옵션

