version: "3"

services:
  ### [Reverse Proxy Server]
  proxy:
    container_name: nginx
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./staging/certbot/conf:/etc/letsencrypt
      - ./staging/certbot/www:/var/www/certbot
    networks:
      - zempot-net
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  ### [SSL]
  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: always
    volumes:
      - ./staging/certbot/conf:/etc/letsencrypt
      - ./staging/certbot/www:/var/www/certbot
    networks:
      - zempot-net
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  # internal:
  zempot-net:
    external: true # 새 network 가 만들어지지 않고, 기존 network 에 연결되게 하는 옵션

